name: DBConnector
version: 1.0.0
main: mc.tsukimiya.dbconnector.DBConnector
description: DB接続用プラグイン
author: deceitya
website: https://github.com/TsukimiyaProject/DBConnector
api-version: 1.21
load: POSTWORLD
libraries:
  - org.jetbrains.kotlin:kotlin:kotlin-stdlib:2.2.0
  - com.zaxxer:HikariCP:6.3.0
  - com.mysql:mysql-connector-j:9.3.0
  - org.xerial:sqlite-jdbc:3.50.3.0
